# Generated by Django 4.1.4 on 2022-12-18 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('attack_status', models.CharField(choices=[('NEW', 'New'), ('RUNNING', 'Running'), ('DONE', 'Done')], default='NEW', max_length=10)),
                ('startTimestamp', models.DateTimeField(auto_now_add=True)),
                ('command', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('attack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attacks.attack')),
            ],
        ),
    ]
