# Generated by Django 4.1.4 on 2022-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0002_rename_attack_status_attack_status_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('STOPPED', 'Stopped')], default='NEW', max_length=10),
        ),
    ]
